### ISSUE TITLE
Admin: chart settings pop up upgrade

### ISSUE THREAD

**Issue by Vo-Vik** [mathgizmo/gizmo#154]
1) bug: When switch between tabs "General Settings" tab does not store selected values

2) improvement : We should be able to edit previously stored config. Please investigate if it is possible to click in corresponding code and have stored settings preloaded in popup

**Comment by odonata95** [comment]
Fix bug with reset values to defaults when tab changed.
Now values will be reseted to defaults only if you change chart type.
cc399487e75aff2a98a27331bb90dbf87ef797d5

**Comment by odonata95** [comment]
For now it preload stored settings from chart string to dialog popup if chart string already exists (else it use default settings).
In future I'll investigate if it is possible to click in corresponding code and have popup opened.
