### ISSUE TITLE
Admin: Redesign question table part1

### ISSUE THREAD

**Issue by Vo-Vik** [mathgizmo/gizmo#19]
table should be split, answers options should be moved to separate table
answers:
- id
- question_id
- value
- is_correct [0/1]
Modify admin interface and API to suport this changes

**Comment by mnhminto** [comment]
Ok . I will create an answer table and relate the answer table with question table depending on question_id. From where the is_correct value is coming from? Write two lines about it.

**Comment by Vo-Vik** [comment]
Also please add order field to described answer table
So. Here how transition should happend. 
For plain text questions, we will have only one record in answer table. With value from old answer field, flag is_correct should be set to 1 and order field set to 0.
For multychoice question, do the same for old answer field, and create extra records for each Answer2-6 and mcq1-6 record, with flag is correct set to 0, and order field set to null or 0. 
If we have question where we have to sort answers, all answers should have flag is_correct set to 1, and order field set with values that match expecting order of the answer.
Do we have any other type that should be converted?

**Comment by Vo-Vik** [comment]
For true or false have correct answer record in answer table.
For multipart questions, we will use same answers rules as for sorting questions.

**Comment by mnhminto** [comment]
Type of Question (3) ------ Reply Modes 

1) Text Only                   ---- General (Question that will have a short answer, will display the question )
                                                   is_correct = 1, order = 0 (User do not input those values, system will 
                                                   automatically set this values? We do not need any form field for it).
                                      ---- True /False
                                                 is_correct = 1, order = 0 (User do not input those values, system will 
                                                   automatically set this values? We do not need any form field for it).

                                      ---- Fill In The Blanks
                                                      is_correct = 1, order= ????
                                      ----  Multiple Choice (Single or Multiple correct answers)
                                                 is_correct = 0, order = 0;
                                      ---- Ascending Order
                                                   is_correct = 1, order= ????
                                      ---- Descending Order
                                              is_correct = 1, order= ????
2) Image                      ----- same six reply mode
3) Dynamic Drawing   ------ same six reply mode

**Comment by Vo-Vik** [comment]
Done
