### ISSUE TITLE
CI: Feedback functionality

### ISSUE THREAD

**Issue by Vo-Vik** [mathgizmo/gizmo#242]
Add "Feedback" button to the pop-up for correct answer; the button takes the user to the same place as the "report error" button.  And,  below is a zip file with new images for the correct/incorrect from back in August.  They are the ones that should be used.
[correct incorrect images v3.zip](https://github.com/mathgizmo/gizmo/files/2636220/correct.incorrect.images.v3.zip)

Use error reporting api, but instead of showing options of possible errors just show text area to enter feed back. Add field in errors DB to indicate that that is feedback, not error

**Comment by odonata95** [comment]
Make Feedback button red, as in the pop-up for incorrect answer.

Currently you can see entered feedbacks in "Error reports" section with option feedback. Should we split this pages? Just thinking if we do not have too many pages already.

We need to come up with nicer buttons for 'continue' and 'report error' and feedback.
