### ISSUE TITLE
CI: slider and charts animations upgrade

### ISSUE THREAD

**Issue by Vo-Vik** [mathgizmo/gizmo#245]
right now value are changed on click. we should allow user drag as well. So please add corresponding animation on mouse down and move. thanks

**Comment by odonata95** [comment]
Sliders and other 'dynamic elements' need to slide when using a tablet or phone. Currently one
needs to point to where you want the endpoint to be.

_Explanation:_ [HTML5 Drag & Drop not works on mobile devices](https://caniuse.com/#search=Drag%20and%20Drop), so we need to use some library for this.

**Comment by odonata95** [comment]
Change dynamic image to respond to touch screen not just to mouse click.
If there is a slider then the both should change with movement (instantly) not just on release.
