### ISSUE TITLE
CI: pop up blocks the question

### ISSUE THREAD

**Issue by odonata95** [mathgizmo/gizmo#247]
When the response to 'answer' pops up as correct or incorrect it blocks the question making it
difficult for the user to reflect on their answer -
Solution 1: make the response box movable by user
Solution 2: put the question into the answer box.
![untitled](https://user-images.githubusercontent.com/18406237/51473723-d604b780-1d85-11e9-8443-02cb69296853.jpg)

**Comment by Vo-Vik** [comment]
Please make popup movable, how ever does not allow user to interact with rest of the page till popup is open
