### ISSUE TITLE
Admin: add ability to change home page information from settings

### ISSUE THREAD

**Issue by odonata95** [mathgizmo/gizmo#262]
We need admin access to the registration and intro pages through admin;
In admin/settings page: add 3 text fields for home page, Home1, Home2, Home3 so that Taras
and Miroslav can change home page information. Create migration that will put current text in
that field.

**Comment by Vo-Vik** [comment]
@odonata95 
Sorry for misunderstanding, this should be settings in admin that control welcome page in ci.
