### ISSUE TITLE
Answer rounding

### ISSUE THREAD

**Issue by Vo-Vik** [mathgizmo/gizmo#277]
Convert checkbox "Round user answer with same precision as correct answer", to radio buttons:
* "Do not round"(this should be default option)
* "Round user answer with same precision as correct answer"(this should be selected if current checkbox is checked)
* "Round Answers up to N digits after point" (if this option selected it should show input field to enter N, default value should be 2)
In CI remember to round both question answer and user answer with same accuracy.

**Comment by odonata95** [comment]
It seems like this functionality already exists, when you check "Convert user answer to decimal value" checkbox it shows input field to enter N, default value was 0 (i've changed it to 2).
