### ISSUE TITLE
Enhancements to the Teacher/ Classes Functionality

### ISSUE THREAD

**Issue by olhachemerynska** [mathgizmo/gizmo#293]

**Comment by odonata95** [comment]
- [x] Change wording in admin 'edit assignment'. “Lessons could be completed in their order” to the following one: "Topics/Lessons need to be completed in linear order." “Lessons could be completed in any order” to the following one:  "Topics/Lessons can be completed in any order."
- [x] Switch order of buttons on answer window: 'report error' on the left and 'continue' on the right.
- [x] Add field AssignmentId into the Tracking Table in the DB. Tracking “Done” (completed) lessons using AsignmentsId.
- [ ] CI: Add +/- buttons for the lessons with slider in the answer (it is difficult to set the correct answer on mobile devices).
- [x] CI>Manage Assignments>Edit page add input field with following title and explanation: “Number of attempts to testout (-1 – means unlimited attempts: 0 – for not testout) ”. “-1” value should be set to the field as default. 
- [x] CI>Manage Classes->invitation only option. Email list should support ",",";" and new line as separator for students emails.
- [x] Hide CI>Home page. Add Dashboard page instead. Dashboard page should be configured the same as Welcome page by using Admin>Setting>Settings (Welcome page texts). For Dashboard page should be the following fields: Dashboard Title and Dashboard Text (read HTML). 
- [ ] CI: Manage Classes. Add link to “Detailed Report” page. Available statuses: overdue, in progress, complete.
- [x] Add student’s country (Canada by default)
- [x] Add ability to register as teacher

**Comment by odonata95** [comment]
For [Google ReCaptcha](https://www.google.com/recaptcha/about/) you need to set your keys in **laravel/.env**:
RECAPTCHA_KEY=your_key
RECAPTCHA_SECRET=your_secret
and in **ci/src/environments/environment.ts**:
captchaKey: 'your_key'
