### ISSUE TITLE
New Structure of application for teacher

### ISSUE THREAD

**Issue by olhachemerynska** [mathgizmo/gizmo#294]

**Comment by odonata95** [comment]
**Menu** should include the following sections: 
- **Home section**
- **Classrooms section**
- **Review Content section**
After clicking on **Classrooms** section the list of all classes is displayed. After clicking on any class user redirect to the Dashoboard page and the following subsections are displayed on the menu bar: 
- **Dashboard** subsection should display list of assignments added to this class
- **Students** subsection should displayed the students list
- **Assignments** subsection should include the assignments list
- **Report** subsection should include reports
- **What a student see** subsection should include assignments list (like in TO DO section for students) with the ability to try them.
