### ISSUE TITLE
CI: Create register functionality

### ISSUE THREAD

**Issue by Vo-Vik** [mathgizmo/gizmo#34]
On login page we should have link to Register action that will use /api/register API call to register users. After registration, user should automatically logged in with saved token from login action. And then redirected to home page.

**Comment by KostyaTretyak** [comment]
For this purpose, the backend should send some session data to the client, such as its userId, nickname, etc.

**Comment by Vo-Vik** [comment]
First we it should send registration request
/api/register in next format {"email":"myemail@gmail.com","password":"password","name":"User name"}
Which should return response in next format
{
    "success": true,
    "message": {
        "name": "User name",
        "email": "myemail@gmail.com",
        "updated_at": "2017-10-22 12:33:13",
        "created_at": "2017-10-22 12:33:13",
        "id": 1
    },
    "status_code": 200
}
if status code 200, success = true and id isset in message, then use logic from https://github.com/mathgizmo/gizmo/blob/master/ci/src/app/login/login.component.ts to get token
